on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cashapp/activate-hermit@v1
      - run: |
          find . -name go.mod | xargs -n1 dirname | while read dir; do (
            cd "$dir"
            go mod tidy
            go test -v ./...
          ); done
          git diff
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cashapp/activate-hermit@v1
      - run: |
          find . -name go.mod | xargs -n1 dirname | while read dir; do (
            cd "$dir"
            go mod tidy
            golangci-lint run
          ); done
          git diff
